server:
  servlet:
    session:
      persistent: false
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://codesver.cfo0oageyl2q.ap-northeast-2.rds.amazonaws.com:3306/am_blog
    username: codesver
    password: wodnjs0716!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true